#!/bin/bash

cd /home/pi/nycts-unit
sudo python reset.py &
sudo python load.py &

cd /home/pi/nycts-unit/headless
sudo npm run start

STATE="loading";
i=0;
offline=false;
while [ $STATE == "loading" ]
do
	i++
    #do a ping and check that its not a default message or change to grep for something else
    STATE=$(ping -q -W 1 -c 1 google.com > /dev/null && echo ok || echo loading)

    #sleep for 1 seconds and try again
    sleep 5

    if [ $i == 10 ]; then
			offline=true
		fi
done

cd /home/pi/nycts-unit/api
node bonjour.js &
node index.js &
pkill -f load.py
sleep 10
cd /home/pi/nycts-unit
sudo python start.py &
sudo /etc/init.d/avahi-daemon restart

while true; do
	sleep 60
	pkill -f bonjour.js
	sleep 1
	cd /home/pi/nycts-unit/api
	node bonjour.js &
done
